name: Test

on: [ push, pull_request ]

jobs:

    Tests:
        uses: 'TYPO3-Console/TYPO3-Console/.github/workflows/TYPO3Build.yml@develop'

        with:
            name: 'T3 ${{ matrix.typo3 }} - PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}'
            typo3: '${{ matrix.typo3 }}'
            php: '${{ matrix.php }}'
            dependency-version: '${{ matrix.dependency-version }}'
            experimental: '${{ matrix.experimental }}'
            uses-db: true
            pre-install: 'echo pre-install done'
            post-install: 'echo post-install done'
            lint: '.Build/bin/parallel-lint --exclude .Build .'
            test: |
                echo 'before test'
                .Build/bin/phpunit
                echo 'after test'
            experimental-test: '.Build/bin/phpunit || true'

        strategy:
            fail-fast: false
            matrix:
                typo3: [ '^11.5.3' ]
                php: [ '7.4', '8.0' ]
                dependency-version: [ lowest, stable ]
                experimental: [ false ]
                include:
                    -   php: 7.4
                        typo3: dev-main
                        dependency-version: stable
                        experimental: true
                    -   php: 8.0
                        typo3: dev-main
                        dependency-version: stable
                        experimental: true

        continue-on-error: ${{ matrix.experimental }}

#            # This fails when command reference is not up to date
#            -   name: Test Command Reference
#                run: |
#                    ./typo3cms commandreference:render > /dev/null 2>&1 && test -z "$(git diff --shortstat 2> /dev/null | tail -n1)"
#
#            -   name: Test Install
#                run: './typo3cms install:setup --database-host-name=127.0.0.1 --database-user-name=root --database-user-password=root --database-name=typo3_test_ci_github  --admin-user-name=admin --admin-password=password --no-interaction -vvv'
#
#            -   name: Test
#                if: '!matrix.experimental'
#                run: .Build/bin/phpunit
#
#            -   name: Test allow failure
#                if: 'matrix.experimental'
#                run: .Build/bin/phpunit || true
